<!doctype html>
<html><head><meta charset="utf-8"><title>{{ $q->quotation_no }}</title>
<style>
@page{size:A4;margin:104px 38px 118px 38px}*{font-family:DejaVu Sans,sans-serif;box-sizing:border-box}body{font-size:10.5px;color:#21384d;margin:0}.doc-head{width:100%;margin:0 0 14px;border-bottom:2px solid #0b73c9;padding-bottom:9px}.doc-title{font-size:20px;font-weight:800;letter-spacing:1px;color:#17324d}.doc-no{font-size:11px;color:#ef1b2d;font-weight:700}.meta-table{width:100%;border-collapse:collapse;margin:0 0 13px}.meta-table td{border:0;padding:2px 0;vertical-align:top}.right{text-align:right}.muted{color:#6e8091}.client-box{border:1px solid #dfe9f2;background:rgba(255,255,255,.94);padding:10px 12px;margin-bottom:14px}.client-title{font-size:9px;letter-spacing:.08em;text-transform:uppercase;color:#718096;font-weight:700;margin-bottom:5px}.client-name{font-size:12px;font-weight:800;color:#17324d}.items{width:100%;border-collapse:collapse;margin-bottom:12px}.items thead{display:table-header-group}.items tr{page-break-inside:avoid}.items th{background:#0b73c9;color:#fff;font-weight:700;padding:7px 6px;border:1px solid #0b73c9}.items td{padding:7px 6px;border:1px solid #dfe7ef;vertical-align:top}.items tbody tr:nth-child(even){background:#f8fbfe}.amount{text-align:right;white-space:nowrap}.center{text-align:center}.summary{width:42%;margin-left:auto;border-collapse:collapse}.summary td{border:0;padding:3px 5px}.summary .label{color:#66798c}.summary .grand td{border-top:1px solid #cfdbe6;padding-top:7px;font-size:12px;font-weight:800;color:#17324d}.summary .grand .amount{color:#ef1b2d}.section{margin-top:12px;border-top:1px solid #dfe7ef;padding-top:8px}.section-title{font-size:9px;text-transform:uppercase;letter-spacing:.08em;font-weight:800;color:#0b73c9;margin-bottom:4px}.signature{margin-top:30px;width:100%}.signature td{border:0;width:50%;padding-top:25px}.sig-line{border-top:1px solid #8595a4;width:170px;padding-top:5px;font-size:9px;color:#657789}.status{display:inline-block;padding:3px 7px;border:1px solid #d9e5ef;border-radius:99px;background:#fff;font-size:9px}.page-break{page-break-before:always}
</style></head><body>
@php
$money=fn($v)=>number_format((float)$v,2);
@endphp
@include('backend.partials.pdf-company-brand', ['business' => $business ?? null])
<table class="doc-head"><tr><td><div class="doc-title">QUOTATION</div><div class="doc-no">{{ $q->quotation_no }}</div></td><td class="right">@if($q->statusStage)<span class="status">{{ $q->statusStage->name }}</span>@endif</td></tr></table>
<table class="meta-table"><tr><td><b>Issue Date:</b> {{ optional($q->issue_date)->format('d M Y') }}<br><b>Valid Until:</b> {{ optional($q->valid_until)->format('d M Y') ?: '-' }}</td><td class="right"><b>Currency:</b> {{ $q->currency }}<br><b>Prepared By:</b> {{ $q->preparedBy?->name ?? '-' }}</td></tr></table>
<div class="client-box"><div class="client-title">Quotation To</div><div class="client-name">{{ $q->client_name ?: 'N/A' }}</div>@if($q->client_phone)<div>{{ $q->client_phone }}</div>@endif @if($q->client_email)<div>{{ $q->client_email }}</div>@endif @if($q->client_address)<div class="muted">{{ $q->client_address }}</div>@endif</div>
<table class="items"><thead><tr><th style="width:34px">#</th><th>Item Description</th><th style="width:60px" class="center">Qty</th><th style="width:86px" class="amount">Unit Price</th><th style="width:58px" class="amount">Tax</th><th style="width:96px" class="amount">Amount</th></tr></thead><tbody>
@foreach($q->items as $i=>$it)<tr><td class="center">{{ $i+1 }}</td><td><b>{{ $it->item_name }}</b>@if($it->description)<div class="muted">{{ $it->description }}</div>@endif</td><td class="center">{{ $it->qty }} {{ $it->unit }}</td><td class="amount">{{ $money($it->unit_price) }}</td><td class="amount">{{ $money($it->tax_rate) }}%</td><td class="amount"><b>{{ $money($it->line_total) }}</b></td></tr>@endforeach
</tbody></table>
<table class="summary"><tr><td class="label">Sub Total</td><td class="amount">{{ $money($q->sub_total) }}</td></tr><tr><td class="label">Discount</td><td class="amount">{{ $money($q->discount_amount) }}</td></tr><tr><td class="label">VAT / Tax</td><td class="amount">{{ $money($q->tax_amount) }}</td></tr><tr class="grand"><td>Grand Total</td><td class="amount">{{ $money($q->grand_total) }} {{ $q->currency }}</td></tr></table>
@if($q->description)<div class="section"><div class="section-title">Description</div>{!! nl2br(e($q->description)) !!}</div>@endif
@if($q->note_for_recipient)<div class="section"><div class="section-title">Note</div>{!! nl2br(e($q->note_for_recipient)) !!}</div>@endif
@if($q->terms)<div class="section"><div class="section-title">Terms & Conditions</div>{!! nl2br(e($q->terms)) !!}</div>@endif
<table class="signature"><tr><td><div class="sig-line">Prepared / Authorized By</div></td><td class="right"><div class="sig-line" style="margin-left:auto">Customer Acceptance</div></td></tr></table>
</body></html>
