@extends('backend.master')
@section('title','User History')
@section('maincontent')
<div class="nxl-content"><div class="page-header"><div><h4 class="mb-1">{{ $user->name }} - Complete History</h4><small class="text-muted">{{ $user->branch?->branch_name ?? '-' }} · {{ $user->phone }}</small></div></div></div>
<div class="main-content">
<div class="card mb-3"><div class="card-body"><form class="row g-2"><div class="col-md-3"><label>Date From</label><input type="date" name="from_date" value="{{ request('from_date') }}" class="form-control"></div><div class="col-md-3"><label>Date To</label><input type="date" name="to_date" value="{{ request('to_date') }}" class="form-control"></div><div class="col-md-4"><label>Search</label><input name="q" value="{{ request('q') }}" class="form-control" placeholder="Search this user's history"></div><div class="col-md-2 d-flex align-items-end gap-2"><button class="btn btn-primary">Filter</button><a href="{{ route('users.history',$user->id) }}" class="btn btn-light">Reset</a></div></form></div></div>
<ul class="nav nav-tabs" role="tablist">@foreach(['activities'=>'Activities','leads'=>'Leads','followups'=>'Lead Follow-ups','sales'=>'Sales','organizations'=>'Organizations Created'] as $k=>$label)<li class="nav-item"><button class="nav-link {{ $loop->first?'active':'' }}" data-bs-toggle="tab" data-bs-target="#{{ $k }}">{{ $label }}</button></li>@endforeach</ul>
<div class="tab-content card border-top-0"><div class="tab-pane fade show active p-3" id="activities"><div class="table-responsive"><table class="table"><thead><tr><th>Date</th><th>Organization</th><th>Contact</th><th>Visit Output</th><th>Distance</th><th>Status</th></tr></thead><tbody>@forelse($activities as $r)<tr><td>{{ optional($r->activity_at)->format('d M Y h:i A') }}</td><td>{{ $r->organization_name ?: ($r->organization?->name ?? '-') }}</td><td>{{ $r->contact_person ?: '-' }}</td><td>{{ Str::limit(strip_tags($r->work_details),80) }}</td><td>{{ $r->distance }} KM</td><td>{{ ucfirst($r->status) }}</td></tr>@empty<tr><td colspan="6" class="text-center">No data</td></tr>@endforelse</tbody></table></div>{{ $activities->links() }}</div>
<div class="tab-pane fade p-3" id="leads"><div class="table-responsive"><table class="table"><thead><tr><th>Date</th><th>Lead</th><th>Contact Person</th><th>Organization</th><th>State</th></tr></thead><tbody>@forelse($leads as $r)<tr><td>{{ $r->created_at->format('d M Y') }}</td><td>{{ $r->lead_no }}</td><td>{{ $r->person_name }}</td><td>{{ $r->organization?->name ?? '-' }}</td><td>{{ ucfirst($r->lead_state) }}</td></tr>@empty<tr><td colspan="5" class="text-center">No data</td></tr>@endforelse</tbody></table></div>{{ $leads->links() }}</div>
<div class="tab-pane fade p-3" id="followups"><div class="table-responsive"><table class="table"><thead><tr><th>Date/Time</th><th>Lead</th><th>Organization</th><th>Action</th><th>Message / Note</th><th>Outcome</th></tr></thead><tbody>@forelse($followups as $r)<tr><td>{{ optional($r->activity_at)->format('d M Y h:i A') }}</td><td>{{ $r->lead?->lead_no ?? '-' }}</td><td>{{ $r->lead?->organization?->name ?? '-' }}</td><td>{{ ucfirst($r->activity_type) }}</td><td>{{ Str::limit($r->activity_text,100) }}</td><td>{{ $r->outcome_status ?: '-' }}</td></tr>@empty<tr><td colspan="6" class="text-center">No data</td></tr>@endforelse</tbody></table></div>{{ $followups->links() }}</div>
<div class="tab-pane fade p-3" id="sales"><div class="table-responsive"><table class="table"><thead><tr><th>Date</th><th>Sale</th><th>Client</th><th>Organization</th><th>Total</th><th>Payment</th></tr></thead><tbody>@forelse($sales as $r)<tr><td>{{ optional($r->sale_date)->format('d M Y') }}</td><td>{{ $r->sale_no }}</td><td>{{ $r->client_name }}</td><td>{{ $r->organization?->name ?? '-' }}</td><td>{{ number_format($r->grand_total,2) }}</td><td>{{ ucfirst($r->payment_status) }}</td></tr>@empty<tr><td colspan="6" class="text-center">No data</td></tr>@endforelse</tbody></table></div>{{ $sales->links() }}</div>
<div class="tab-pane fade p-3" id="organizations"><div class="table-responsive"><table class="table"><thead><tr><th>Date</th><th>Organization</th><th>Phone</th><th>Status</th></tr></thead><tbody>@forelse($organizations as $r)<tr><td>{{ $r->created_at->format('d M Y') }}</td><td>{{ $r->name }}</td><td>{{ $r->phone_primary ?: '-' }}</td><td>{{ ucfirst($r->status) }}</td></tr>@empty<tr><td colspan="4" class="text-center">No data</td></tr>@endforelse</tbody></table></div>{{ $organizations->links() }}</div></div>
</div>@endsection