@extends('backend.master')
@section('title','Lead Details & History')
@section('maincontent')
<div class="nxl-content"><div class="page-header"><div class="page-header-title"><h5 class="m-b-10">Lead Details & History</h5><ul class="breadcrumb"><li class="breadcrumb-item"><a href="{{ route('leads.index') }}">Leads</a></li><li class="breadcrumb-item">{{ $lead->lead_no }}</li></ul></div><div class="page-header-right ms-auto"><a href="{{ route('leads.index') }}" class="btn btn-light"><i class="feather-arrow-left me-1"></i> Back to Leads</a></div></div></div>
<div class="main-content lead-history-page">
<div class="card lead-hero mb-4"><div class="card-body p-4"><div class="row g-4 align-items-center"><div class="col-lg-7"><div class="d-flex align-items-start gap-3"><div class="lead-avatar">{{ strtoupper(substr($lead->person_name ?: 'L',0,1)) }}</div><div><div class="d-flex flex-wrap gap-2 align-items-center"><h4 class="mb-0">{{ $lead->person_name ?: '-' }}</h4><span class="badge bg-primary-subtle text-primary">{{ $lead->lead_no }}</span>@if($lead->statusStage)<span class="badge" style="background:{{ $lead->statusStage->color ?: '#6c757d' }}">{{ $lead->statusStage->name }}</span>@endif</div><div class="text-muted mt-2">{{ $lead->subject ?: 'No subject' }}</div></div></div><div class="row mt-4 g-3 info-grid"><div class="col-md-6"><span>Phone</span><strong>{{ $lead->person_phone ?: '-' }}</strong></div><div class="col-md-6"><span>Email</span><strong>{{ $lead->person_email ?: '-' }}</strong></div><div class="col-md-6"><span>Organization</span><strong>{{ $lead->organization->name ?? '-' }}</strong></div><div class="col-md-6"><span>Contact Person</span><strong>{{ $lead->organizationContact->name ?? $lead->person_name ?? '-' }}</strong></div><div class="col-md-6"><span>Created By</span><strong>{{ $lead->creator->name ?? '-' }}</strong></div><div class="col-md-6"><span>Assigned To</span><strong>{{ $lead->assignedUser->name ?? '-' }}</strong></div><div class="col-md-6"><span>Created At</span><strong>{{ optional($lead->created_at)->format('d M Y, h:i A') }}</strong></div><div class="col-md-6"><span>Lead State</span><strong>{{ ucfirst($lead->lead_state ?: '-') }}</strong></div></div></div>
<div class="col-lg-5"><div class="row g-3"><div class="col-4"><div class="summary-box"><i class="feather-activity"></i><h3>{{ $activityCount }}</h3><span>Activities</span></div></div><div class="col-4"><div class="summary-box"><i class="feather-clock"></i><h3>{{ $followupCount }}</h3><span>Follow-ups</span></div></div><div class="col-4"><div class="summary-box"><i class="feather-shopping-bag"></i><h3>{{ $saleCount }}</h3><span>Sales</span></div></div></div></div></div></div></div>
<div class="card"><div class="card-body p-0"><ul class="nav nav-tabs history-tabs px-3 pt-3" role="tablist"><li class="nav-item"><button class="nav-link active" data-bs-toggle="tab" data-bs-target="#timeline">Complete Timeline <span class="badge bg-light text-dark">{{ $activityCount }}</span></button></li><li class="nav-item"><button class="nav-link" data-bs-toggle="tab" data-bs-target="#sales">Sales <span class="badge bg-light text-dark">{{ $saleCount }}</span></button></li><li class="nav-item"><button class="nav-link" data-bs-toggle="tab" data-bs-target="#info">Lead Information</button></li></ul><div class="tab-content p-4">
<div class="tab-pane fade show active" id="timeline">@forelse($activities as $a)<div class="timeline-row"><div class="timeline-icon"><i class="feather-clock"></i></div><div class="timeline-card"><div class="d-flex flex-wrap justify-content-between gap-2"><div><strong>{{ ucfirst($a->activity_type ?: 'Activity') }}</strong>@if($a->outcome_status)<span class="badge bg-light text-dark ms-2">{{ $a->outcome_status }}</span>@endif</div><small class="text-muted">{{ optional($a->activity_at)->format('d M Y, h:i A') }}</small></div><p class="mb-1 mt-2">{{ $a->activity_text ?: '-' }}</p><small class="text-muted">Created by: {{ $a->creator->name ?? '-' }}</small>@if($a->next_followup_at)<div class="next-followup mt-2"><i class="feather-calendar"></i> Next: {{ $a->next_followup_at->format('d M Y, h:i A') }} @if($a->next_action_type) · {{ ucfirst($a->next_action_type) }} @endif</div>@endif</div></div>@empty<div class="empty-state">No activity/follow-up history found.</div>@endforelse<div class="mt-3">{{ $activities->links() }}</div></div>
<div class="tab-pane fade" id="sales"><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Sale No</th><th>Date</th><th>Sold By</th><th>Grand Total</th><th>Paid</th><th>Due</th><th>Status</th></tr></thead><tbody>@forelse($sales as $sale)<tr><td><strong>{{ $sale->sale_no ?: $sale->invoice_no }}</strong></td><td>{{ optional($sale->sale_date)->format('d M Y') }}</td><td>{{ $sale->soldBy->name ?? '-' }}</td><td>{{ number_format((float)$sale->grand_total,2) }}</td><td>{{ number_format((float)$sale->paid_total,2) }}</td><td>{{ number_format((float)$sale->due_total,2) }}</td><td>{{ $sale->payment_status ?: ($sale->statusStage->name ?? '-') }}</td></tr>@empty<tr><td colspan="7" class="text-center py-5 text-muted">No related sales found.</td></tr>@endforelse</tbody></table></div><div class="mt-3">{{ $sales->links() }}</div></div>
<div class="tab-pane fade" id="info"><div class="row g-3 info-grid"><div class="col-md-6"><span>Platform</span><strong>{{ $lead->platform->title ?? '-' }}</strong></div><div class="col-md-6"><span>Expected Value</span><strong>{{ number_format((float)$lead->expected_value,2) }}</strong></div><div class="col-md-6"><span>Next Follow-up</span><strong>{{ optional($lead->next_followup_at)->format('d M Y, h:i A') ?: '-' }}</strong></div><div class="col-md-6"><span>Next Action</span><strong>{{ ucfirst($lead->next_action_type ?: '-') }}</strong></div><div class="col-12"><span>Existing Machine</span><strong class="d-block mt-1">{{ $lead->existing_machine ?: '-' }}</strong></div><div class="col-12"><span>Note</span><strong class="d-block mt-1">{{ $lead->note ?: '-' }}</strong></div></div></div>
</div></div></div></div>
@endsection
@push('styles')
<style>.lead-history-page .card{border:1px solid #e8edf3;border-radius:12px;box-shadow:0 4px 18px rgba(16,24,40,.04)}.lead-avatar{width:52px;height:52px;border-radius:50%;display:flex;align-items:center;justify-content:center;background:#e8f1ff;color:#2563eb;font-size:20px;font-weight:800;flex:0 0 52px}.info-grid span{display:block;color:#7a8699;font-size:12px;margin-bottom:3px}.info-grid strong{color:#26364a;font-weight:600}.summary-box{height:135px;border:1px solid #e3e9f1;border-radius:12px;padding:18px;background:#fbfdff}.summary-box i{font-size:20px;color:#2563eb}.summary-box h3{font-size:26px;margin:12px 0 0}.summary-box span{font-size:12px;color:#667085}.history-tabs .nav-link{border:0;border-bottom:2px solid transparent;color:#526174;font-weight:600}.history-tabs .nav-link.active{color:#2563eb;border-bottom-color:#2563eb;background:transparent}.timeline-row{position:relative;padding-left:48px;margin-bottom:18px}.timeline-icon{position:absolute;left:0;top:4px;width:34px;height:34px;border-radius:50%;background:#eef4ff;color:#2563eb;display:flex;align-items:center;justify-content:center}.timeline-row:before{content:'';position:absolute;left:16px;top:38px;bottom:-22px;width:2px;background:#edf0f4}.timeline-row:last-child:before{display:none}.timeline-card{border:1px solid #e8edf3;border-radius:10px;padding:16px;background:#fff}.next-followup{font-size:12px;color:#526174;background:#f7f9fc;border-radius:7px;padding:8px 10px}.empty-state{text-align:center;padding:50px;color:#8b95a5}@media(max-width:767px){.summary-box{height:auto;padding:12px}.summary-box h3{font-size:20px}.tab-content{padding:15px!important}.timeline-row{padding-left:42px}}</style>
@endpush
