<!doctype html>
<html><head><meta charset="utf-8"><title>Invoice - {{ $sale->invoice_no }}</title>
<style>
@page{size:A4;margin:104px 38px 118px 38px}*{font-family:DejaVu Sans,sans-serif;box-sizing:border-box}body{font-size:10.5px;color:#21384d;margin:0}.doc-head{width:100%;margin:0 0 14px;border-bottom:2px solid #0b73c9;padding-bottom:9px}.doc-title{font-size:20px;font-weight:800;letter-spacing:1px;color:#17324d}.doc-no{font-size:11px;color:#ef1b2d;font-weight:700}.meta{width:100%;border-collapse:collapse;margin-bottom:13px}.meta td{border:0;padding:2px 0;vertical-align:top}.right{text-align:right}.center{text-align:center}.muted{color:#6e8091}.bill-box{border:1px solid #dfe9f2;background:rgba(255,255,255,.94);padding:10px 12px;margin-bottom:14px}.label{font-size:9px;letter-spacing:.08em;text-transform:uppercase;color:#718096;font-weight:700;margin-bottom:5px}.client{font-size:12px;font-weight:800;color:#17324d}.status{display:inline-block;padding:3px 7px;border:1px solid #d9e5ef;border-radius:99px;background:#fff;font-size:9px;margin-left:4px}.items{width:100%;border-collapse:collapse;margin-bottom:12px}.items thead{display:table-header-group}.items tr{page-break-inside:avoid}.items th{background:#0b73c9;color:#fff;font-weight:700;padding:7px 6px;border:1px solid #0b73c9}.items td{padding:7px 6px;border:1px solid #dfe7ef;vertical-align:top}.items tbody tr:nth-child(even){background:#f8fbfe}.amount{text-align:right;white-space:nowrap}.summary{width:42%;margin-left:auto;border-collapse:collapse}.summary td{border:0;padding:3px 5px}.summary .k{color:#66798c}.summary .grand td{border-top:1px solid #cfdbe6;padding-top:7px;font-size:12px;font-weight:800}.summary .grand .amount{color:#ef1b2d}.section{margin-top:12px;border-top:1px solid #dfe7ef;padding-top:8px}.section-title{font-size:9px;text-transform:uppercase;letter-spacing:.08em;font-weight:800;color:#0b73c9;margin-bottom:4px}.payment{margin-top:12px;width:100%;border-collapse:collapse}.payment th{background:#f3f7fb;color:#5a6f83}.payment th,.payment td{border:1px solid #dfe7ef;padding:6px}.signature{margin-top:30px;width:100%}.signature td{border:0;width:50%;padding-top:25px}.sig-line{border-top:1px solid #8595a4;width:170px;padding-top:5px;font-size:9px;color:#657789}
</style></head><body>
@php
$money=fn($v)=>number_format((float)$v,2);$bdDate=fn($dt)=>$dt?\Carbon\Carbon::parse($dt)->timezone('Asia/Dhaka')->format('d M Y'):'-';
@endphp
@include('backend.partials.pdf-company-brand', ['business' => $business ?? null, 'showAddress' => false])
<table class="doc-head"><tr><td><div class="doc-title">INVOICE</div><div class="doc-no">{{ $sale->invoice_no }}</div></td><td class="right"><span class="status">{{ strtoupper($sale->payment_status ?? 'unpaid') }}</span>@if($sale->statusStage)<span class="status">{{ $sale->statusStage->name }}</span>@endif</td></tr></table>
<table class="meta"><tr><td><b>Invoice Date:</b> {{ $bdDate($sale->sale_date) }}<br><b>Sale No:</b> {{ $sale->sale_no }}</td><td class="right">@if($sale->branch)<b>Branch:</b> {{ $sale->branch->branch_name }}<br>@endif<b>Sold By:</b> {{ $sale->soldBy?->name ?? '-' }}</td></tr></table>
<div class="bill-box"><div class="label">Bill To</div><div class="client">{{ $sale->client_name ?: 'N/A' }}</div>@if($sale->client_phone)<div>{{ $sale->client_phone }}</div>@endif @if($sale->client_email)<div>{{ $sale->client_email }}</div>@endif @if($sale->client_address)<div class="muted">{{ $sale->client_address }}</div>@endif</div>
<table class="items"><thead><tr><th style="width:34px">#</th><th>Item Description</th><th style="width:60px" class="center">Qty</th><th style="width:86px" class="amount">Unit Price</th><th style="width:58px" class="amount">Tax</th><th style="width:96px" class="amount">Amount</th></tr></thead><tbody>
@foreach($sale->items as $i=>$it)<tr><td class="center">{{ $i+1 }}</td><td><b>{{ $it->item_name }}</b>@if($it->description)<div class="muted">{!! $it->description !!}</div>@endif</td><td class="center">{{ $it->qty }} {{ $it->unit }}</td><td class="amount">{{ $money($it->unit_price) }}</td><td class="amount">{{ $money($it->tax_rate) }}%</td><td class="amount"><b>{{ $money($it->line_total) }}</b></td></tr>@endforeach
</tbody></table>
<table class="summary"><tr><td class="k">Sub Total</td><td class="amount">{{ $money($sale->sub_total) }}</td></tr><tr><td class="k">Discount</td><td class="amount">{{ $money($sale->discount_amount) }}</td></tr><tr><td class="k">VAT / Tax</td><td class="amount">{{ $money($sale->tax_amount) }}</td></tr><tr class="grand"><td>Grand Total</td><td class="amount">{{ $money($sale->grand_total) }}</td></tr><tr><td class="k">Paid</td><td class="amount">{{ $money($sale->paid_total) }}</td></tr><tr><td class="k">Due</td><td class="amount">{{ $money($sale->due_total) }}</td></tr></table>
@if($sale->payments && $sale->payments->count())<div class="section"><div class="section-title">Payment History</div><table class="payment"><thead><tr><th>Date</th><th>Method</th><th>Reference</th><th class="amount">Amount</th></tr></thead><tbody>@foreach($sale->payments as $pay)<tr><td>{{ $bdDate($pay->payment_date ?? $pay->created_at) }}</td><td>{{ $pay->method ?? $pay->payment_method ?? '-' }}</td><td>{{ $pay->transaction_ref ?? '-' }}</td><td class="amount">{{ $money($pay->amount) }}</td></tr>@endforeach</tbody></table></div>@endif
@if($sale->notes)<div class="section"><div class="section-title">Notes</div>{!! nl2br(e($sale->notes)) !!}</div>@endif
<table class="signature"><tr><td><div class="sig-line">Authorized Signature</div></td><td class="right"><div class="sig-line" style="margin-left:auto">Customer Signature</div></td></tr></table>
</body></html>
