@extends('backend.master')
@section('title','Follow-ups')
@section('maincontent')
<div class="nxl-content"><div class="page-header"><div class="page-header-title"><h5 class="m-b-10">Lead Follow-ups</h5></div></div></div>
<div class="main-content">@if(session('message'))<div class="alert alert-success">{{ session('message') }}</div>@endif
<div class="row g-3 mb-3"><div class="col-md-4"><a class="text-decoration-none" href="{{ route('followups.index',['filter'=>'overdue']) }}"><div class="card p-3 border-danger"><small>Overdue</small><h3 class="text-danger mb-0">{{ $counts['overdue'] }}</h3></div></a></div><div class="col-md-4"><a class="text-decoration-none" href="{{ route('followups.index',['filter'=>'today']) }}"><div class="card p-3 border-primary"><small>Today</small><h3 class="text-primary mb-0">{{ $counts['today'] }}</h3></div></a></div><div class="col-md-4"><a class="text-decoration-none" href="{{ route('followups.index',['filter'=>'upcoming']) }}"><div class="card p-3 border-success"><small>Next 7 Days</small><h3 class="text-success mb-0">{{ $counts['upcoming'] }}</h3></div></a></div></div>
<div class="card"><div class="card-body"><form class="row g-2 mb-3" method="GET"><div class="col-md-3"><select name="filter" class="form-control"><option value="today" @selected($filter==='today')>Today</option><option value="overdue" @selected($filter==='overdue')>Overdue</option><option value="upcoming" @selected($filter==='upcoming')>Next 7 Days</option><option value="all" @selected($filter==='all')>All</option></select></div>@can('staff.filter')<div class="col-md-3"><select name="user_id" class="form-control"><option value="">All Staff</option>@foreach($staffs as $staff)<option value="{{ $staff->id }}" @selected((string)request('user_id')===(string)$staff->id)>{{ $staff->name }}</option>@endforeach</select></div>@endcan<div class="col-md-4"><input name="q" value="{{ request('q') }}" class="form-control" placeholder="Search contact, phone, lead no"></div><div class="col-md-2 d-flex gap-1"><button class="btn btn-primary flex-fill">Search</button><a href="{{ route('followups.index') }}" class="btn btn-light">Reset</a></div></form>
<div class="table-responsive"><table class="table align-middle"><thead><tr><th>Contact Person</th><th>Lead / Organization</th><th>Phone</th><th>Created By</th><th>Action</th><th>Follow-up Time</th><th>Message / Note</th></tr></thead><tbody>
@forelse($followups as $lead) @php $overdue=$lead->next_followup_at&&$lead->next_followup_at->isPast()&&!$lead->next_followup_at->isToday(); @endphp
<tr><td><strong>{{ $lead->person_name ?: '-' }}</strong></td><td>@can('lead.details.view')<a href="{{ route('leads.history',$lead->id) }}" class="fw-bold text-primary text-decoration-none">{{ $lead->lead_no }}</a>@else<strong>{{ $lead->lead_no }}</strong>@endcan<br><small>{{ $lead->organization->name ?? '-' }}</small><br><small class="text-muted">{{ Str::limit($lead->subject,55) }}</small></td><td><a href="tel:{{ $lead->person_phone }}">{{ $lead->person_phone ?: '-' }}</a></td><td>{{ $lead->assignedUser->name ?? '-' }}</td><td><span class="badge bg-light text-dark">{{ ucfirst($lead->next_action_type ?: 'follow-up') }}</span></td><td class="{{ $overdue?'text-danger fw-bold':'' }}">{{ optional($lead->next_followup_at)->format('d M Y, h:i A') }}</td><td><div class="d-flex flex-wrap gap-1"><button class="btn btn-success btn-sm" data-bs-toggle="modal" data-bs-target="#done{{ $lead->id }}">Done</button><button class="btn btn-outline-primary btn-sm" data-bs-toggle="modal" data-bs-target="#feedback{{ $lead->id }}">Feedback</button><button class="btn btn-outline-warning btn-sm" data-bs-toggle="modal" data-bs-target="#reschedule{{ $lead->id }}">Reschedule</button>@can('followup.details.view')<a class="btn btn-outline-info btn-sm" href="{{ route('followups.history',$lead->id) }}">History</a>@endcan</div></td></tr>
@empty<tr><td colspan="7" class="text-center py-5 text-muted">No follow-ups found.</td></tr>@endforelse</tbody></table></div>{{ $followups->links() }}</div></div></div>

{{-- IMPORTANT: Modals must be outside <table>/<tbody>. Browsers otherwise repair invalid HTML and can close the form before modal-header/body/footer. --}}
@foreach($followups as $lead)
<div class="modal fade followup-list-modal" id="done{{ $lead->id }}" tabindex="-1" aria-hidden="true"><div class="modal-dialog modal-dialog-centered"><div class="modal-content"><form method="POST" action="{{ route('followups.complete',$lead->id) }}">@csrf<div class="modal-header"><h5 class="modal-title">Complete Follow-up</h5><button class="btn-close" type="button" data-bs-dismiss="modal" aria-label="Close"></button></div><div class="modal-body"><label class="form-label">Outcome</label><select name="outcome_status" class="form-select mb-3" required><option>Interested</option><option>Call Again</option><option>Meeting Fixed</option><option>No Answer</option><option>Not Interested</option><option>Other</option></select><label class="form-label">Message / Note</label><textarea name="activity_text" class="form-control" rows="4"></textarea></div><div class="modal-footer"><button type="button" class="btn btn-light" data-bs-dismiss="modal">Cancel</button><button type="submit" class="btn btn-success">Save</button></div></form></div></div></div>

<div class="modal fade followup-list-modal" id="feedback{{ $lead->id }}" tabindex="-1" aria-hidden="true"><div class="modal-dialog modal-dialog-centered"><div class="modal-content"><form method="POST" action="{{ route('followups.feedback',$lead->id) }}">@csrf<div class="modal-header"><h5 class="modal-title">Add Feedback</h5><button class="btn-close" type="button" data-bs-dismiss="modal" aria-label="Close"></button></div><div class="modal-body"><label class="form-label">Feedback / Remarks *</label><textarea name="feedback" class="form-control" rows="5" required></textarea></div><div class="modal-footer"><button type="button" class="btn btn-light" data-bs-dismiss="modal">Cancel</button><button type="submit" class="btn btn-primary">Save Feedback</button></div></form></div></div></div>

<div class="modal fade followup-list-modal" id="reschedule{{ $lead->id }}" tabindex="-1" aria-hidden="true"><div class="modal-dialog modal-dialog-centered"><div class="modal-content"><form method="POST" action="{{ route('followups.reschedule',$lead->id) }}">@csrf<div class="modal-header"><h5 class="modal-title">Reschedule Follow-up</h5><button class="btn-close" type="button" data-bs-dismiss="modal" aria-label="Close"></button></div><div class="modal-body"><div class="row g-3"><div class="col-md-6"><label class="form-label">New Follow-up Date *</label><input type="date" name="followup_date" class="form-control" required></div><div class="col-md-6"><label class="form-label">New Follow-up Time *</label><input type="time" name="followup_time" class="form-control" required></div><div class="col-12"><label class="form-label">Action</label><select name="next_action_type" class="form-select"><option value="call">Call</option><option value="visit">Visit</option><option value="message">Message</option><option value="meeting">Meeting</option></select></div><div class="col-12"><label class="form-label">Message / Note</label><textarea name="message" class="form-control" rows="4" placeholder="Write message or note..."></textarea></div><div class="col-12"><label class="form-label">Remarks</label><textarea name="remarks" class="form-control" rows="3" placeholder="Write remarks..."></textarea></div></div></div><div class="modal-footer"><button type="button" class="btn btn-light" data-bs-dismiss="modal">Cancel</button><button type="submit" class="btn btn-warning text-white">Complete &amp; Reschedule</button></div></form></div></div></div>
@endforeach
@endsection

@push('styles')
<style>
.followup-list-modal{z-index:1060!important}
.followup-list-modal .modal-dialog{max-width:620px;width:calc(100% - 30px)}
.followup-list-modal .modal-content{background:#fff!important;border:0!important;border-radius:12px!important;box-shadow:0 20px 50px rgba(15,23,42,.22)!important;overflow:hidden;opacity:1!important}
.followup-list-modal .modal-content form{display:flex;flex-direction:column;width:100%;margin:0;background:#fff!important}
.followup-list-modal .modal-header{padding:20px 24px;background:#fff!important;border-bottom:1px solid #e5e7eb!important}
.followup-list-modal .modal-title{margin:0;font-size:18px;font-weight:700;color:#1e293b}
.followup-list-modal .modal-body{padding:24px;background:#fff!important;color:#334155}
.followup-list-modal .modal-footer{padding:16px 24px;background:#fff!important;border-top:1px solid #e5e7eb!important;gap:10px}
.followup-list-modal label{margin-bottom:7px;color:#334155;font-size:14px;font-weight:600}
.followup-list-modal .form-control,.followup-list-modal .form-select{min-height:46px;padding:10px 13px;background:#fff!important;border:1px solid #d7dde5!important;border-radius:7px!important;color:#334155!important;box-shadow:none!important}
.followup-list-modal textarea.form-control{min-height:95px;resize:vertical}
.followup-list-modal .form-control:focus,.followup-list-modal .form-select:focus{border-color:#86b7fe!important;box-shadow:0 0 0 .2rem rgba(13,110,253,.12)!important}
.followup-list-modal .btn{min-height:44px;padding:9px 22px;border-radius:7px;font-weight:600}
.followup-list-modal .btn-light{background:#fff!important;border:1px solid #d7dde5!important;color:#475569!important}
.followup-list-modal .btn-warning{background:#ff9f1a!important;border-color:#ff9f1a!important;color:#fff!important}
.followup-list-modal .btn-warning:hover{background:#f58f00!important;border-color:#f58f00!important}
.modal-backdrop.show{opacity:.45!important}
@media(max-width:767.98px){.followup-list-modal .modal-dialog{width:calc(100% - 20px);margin:10px auto}.followup-list-modal .modal-header,.followup-list-modal .modal-body,.followup-list-modal .modal-footer{padding:16px 18px}.followup-list-modal .modal-footer .btn{flex:1}}
</style>
@endpush
