@extends('backend.master')
@section('title','Follow-ups')
@section('maincontent')
<div class="nxl-content"><div class="page-header"><div class="page-header-title"><h5 class="m-b-10">Lead Follow-ups</h5></div></div></div>
<div class="main-content">@if(session('message'))<div class="alert alert-success">{{ session('message') }}</div>@endif
<div class="row g-3 mb-3"><div class="col-md-4"><a class="text-decoration-none" href="{{ route('followups.index',['filter'=>'overdue']) }}"><div class="card p-3 border-danger"><small>Overdue</small><h3 class="text-danger mb-0">{{ $counts['overdue'] }}</h3></div></a></div><div class="col-md-4"><a class="text-decoration-none" href="{{ route('followups.index',['filter'=>'today']) }}"><div class="card p-3 border-primary"><small>Today</small><h3 class="text-primary mb-0">{{ $counts['today'] }}</h3></div></a></div><div class="col-md-4"><a class="text-decoration-none" href="{{ route('followups.index',['filter'=>'upcoming']) }}"><div class="card p-3 border-success"><small>Next 7 Days</small><h3 class="text-success mb-0">{{ $counts['upcoming'] }}</h3></div></a></div></div>
<div class="card"><div class="card-body"><form class="row g-2 mb-3" method="GET"><div class="col-md-3"><select name="filter" class="form-control"><option value="today" @selected($filter==='today')>Today</option><option value="overdue" @selected($filter==='overdue')>Overdue</option><option value="upcoming" @selected($filter==='upcoming')>Next 7 Days</option><option value="all" @selected($filter==='all')>All</option></select></div>@can('staff.filter')<div class="col-md-3"><select name="user_id" class="form-control"><option value="">All Staff</option>@foreach($staffs as $staff)<option value="{{ $staff->id }}" @selected((string)request('user_id')===(string)$staff->id)>{{ $staff->name }}</option>@endforeach</select></div>@endcan<div class="col-md-4"><input name="q" value="{{ request('q') }}" class="form-control" placeholder="Search contact, phone, lead no"></div><div class="col-md-2 d-flex gap-1"><button class="btn btn-primary flex-fill">Search</button><a href="{{ route('followups.index') }}" class="btn btn-light">Reset</a></div></form>
<div class="table-responsive"><table class="table align-middle"><thead><tr><th>Contact Person</th><th>Lead / Organization</th><th>Phone</th><th>Created By</th><th>Action</th><th>Follow-up Time</th><th>Message / Note</th></tr></thead><tbody>
@forelse($followups as $lead) @php $overdue=$lead->next_followup_at&&$lead->next_followup_at->isPast()&&!$lead->next_followup_at->isToday(); @endphp
<tr><td><strong>{{ $lead->person_name ?: '-' }}</strong></td><td>@can('lead.details.view')<a href="{{ route('leads.history',$lead->id) }}" class="fw-bold text-primary text-decoration-none">{{ $lead->lead_no }}</a>@else<strong>{{ $lead->lead_no }}</strong>@endcan<br><small>{{ $lead->organization->name ?? '-' }}</small><br><small class="text-muted">{{ Str::limit($lead->subject,55) }}</small></td><td><a href="tel:{{ $lead->person_phone }}">{{ $lead->person_phone ?: '-' }}</a></td><td>{{ $lead->assignedUser->name ?? '-' }}</td><td><span class="badge bg-light text-dark">{{ ucfirst($lead->next_action_type ?: 'follow-up') }}</span></td><td class="{{ $overdue?'text-danger fw-bold':'' }}">{{ optional($lead->next_followup_at)->format('d M Y, h:i A') }}</td><td><div class="d-flex flex-wrap gap-1"><button class="btn btn-success btn-sm" data-bs-toggle="modal" data-bs-target="#done{{ $lead->id }}">Done</button><button class="btn btn-outline-primary btn-sm" data-bs-toggle="modal" data-bs-target="#feedback{{ $lead->id }}">Feedback</button><button class="btn btn-outline-warning btn-sm" data-bs-toggle="modal" data-bs-target="#reschedule{{ $lead->id }}">Reschedule</button>@can('followup.details.view')<a class="btn btn-outline-info btn-sm" href="{{ route('followups.history',$lead->id) }}">History</a>@endcan</div></td></tr>
<div class="modal fade" id="done{{ $lead->id }}"><div class="modal-dialog"><form class="modal-content" method="POST" action="{{ route('followups.complete',$lead->id) }}">@csrf<div class="modal-header"><h5>Complete Follow-up</h5><button class="btn-close" type="button" data-bs-dismiss="modal"></button></div><div class="modal-body"><label>Outcome</label><select name="outcome_status" class="form-control mb-3" required><option>Interested</option><option>Call Again</option><option>Meeting Fixed</option><option>No Answer</option><option>Not Interested</option><option>Other</option></select><label>Message / Note</label><textarea name="activity_text" class="form-control" rows="4"></textarea></div><div class="modal-footer"><button class="btn btn-success">Save</button></div></form></div></div>
<div class="modal fade" id="feedback{{ $lead->id }}"><div class="modal-dialog"><form class="modal-content" method="POST" action="{{ route('followups.feedback',$lead->id) }}">@csrf<div class="modal-header"><h5>Add Feedback</h5><button class="btn-close" type="button" data-bs-dismiss="modal"></button></div><div class="modal-body"><label>Feedback / Remarks *</label><textarea name="feedback" class="form-control" rows="5" required></textarea></div><div class="modal-footer"><button class="btn btn-primary">Save Feedback</button></div></form></div></div>
<div class="modal fade" id="reschedule{{ $lead->id }}"><div class="modal-dialog"><form class="modal-content" method="POST" action="{{ route('followups.reschedule',$lead->id) }}">@csrf<div class="modal-header"><h5>Reschedule Follow-up</h5><button class="btn-close" type="button" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="row g-2"><div class="col-6"><label>New Follow-up Date *</label><input type="date" name="followup_date" class="form-control" required></div><div class="col-6"><label>New Follow-up Time *</label><input type="time" name="followup_time" class="form-control" required></div><div class="col-12"><label>Action</label><select name="next_action_type" class="form-control"><option value="call">Call</option><option value="visit">Visit</option><option value="message">Message</option><option value="meeting">Meeting</option></select></div><div class="col-12"><label>Message / Note</label><textarea name="message" class="form-control" rows="3"></textarea></div><div class="col-12"><label>Remarks</label><textarea name="remarks" class="form-control" rows="2"></textarea></div></div></div><div class="modal-footer"><button class="btn btn-warning">Complete & Reschedule</button></div></form></div></div>
@empty<tr><td colspan="7" class="text-center py-5 text-muted">No follow-ups found.</td></tr>@endforelse</tbody></table></div>{{ $followups->links() }}</div></div></div>
@endsection

@push('styles')
<style>
.modal-backdrop.show{opacity:.42}.modal-dialog{margin:1.5rem auto}.modal-content{border:0!important;border-radius:14px!important;box-shadow:0 20px 55px rgba(15,23,42,.18);overflow:hidden}.modal-header{padding:20px 24px;border-bottom:1px solid #e9edf3;background:#fff}.modal-header h5{font-weight:700;margin:0;color:#26364a}.modal-body{padding:24px;background:#fff}.modal-footer{padding:16px 24px;border-top:1px solid #e9edf3;background:#fafbfc;gap:8px}.modal-body label{display:block;font-weight:600;margin-bottom:7px;color:#344054}.modal-body .form-control,.modal-body .form-select{min-height:46px;border:1px solid #d7dee8;border-radius:8px;padding:10px 12px;background:#fff}.modal-body textarea.form-control{min-height:92px}.modal-body .form-control:focus,.modal-body .form-select:focus{border-color:#86b7fe;box-shadow:0 0 0 .2rem rgba(13,110,253,.12)}.modal-footer .btn{min-height:42px;border-radius:7px;font-weight:600;padding:9px 18px}@media(max-width:575.98px){.modal-dialog{margin:.75rem}.modal-body,.modal-header,.modal-footer{padding:16px}.modal-body .col-6{width:100%}.modal-footer .btn{width:100%}}
</style>
@endpush
