@extends('backend.master')
@section('title','My Profile')
@section('maincontent')
<div class="main-content"><div class="page-header"><div class="page-header-title"><h5>My Profile</h5></div></div>
@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
<div class="row g-3">
@can('profile.update')<div class="col-lg-7"><div class="card"><div class="card-header"><h5 class="mb-0">Profile Information</h5></div><div class="card-body"><form method="POST" action="{{ route('profile.update') }}" enctype="multipart/form-data">@csrf
<div class="row g-3"><div class="col-md-6"><label class="form-label">Name *</label><input name="name" class="form-control" value="{{ old('name',$user->name) }}" required></div><div class="col-md-6"><label class="form-label">Email</label><input name="email" type="email" class="form-control" value="{{ old('email',$user->email) }}"></div><div class="col-md-6"><label class="form-label">Phone</label><input name="phone" class="form-control" value="{{ old('phone',$user->phone) }}"></div><div class="col-md-6"><label class="form-label">Profile Photo</label><input name="profile" type="file" accept="image/*" class="form-control"></div><div class="col-12"><label class="form-label">Present Address</label><textarea name="present_address" class="form-control">{{ old('present_address',$user->present_address) }}</textarea></div><div class="col-12"><label class="form-label">Permanent Address</label><textarea name="parmanent_address" class="form-control">{{ old('parmanent_address',$user->parmanent_address) }}</textarea></div></div><button class="btn btn-primary mt-3">Update Profile</button></form></div></div></div>@endcan
@can('profile.change_password')<div class="col-lg-5"><div class="card"><div class="card-header"><h5 class="mb-0">Change Password</h5></div><div class="card-body"><form method="POST" action="{{ route('profile.password.update') }}">@csrf<div class="mb-3"><label class="form-label">Current Password</label><input type="password" name="current_password" class="form-control" required></div><div class="mb-3"><label class="form-label">New Password</label><input type="password" name="password" class="form-control" required></div><div class="mb-3"><label class="form-label">Confirm Password</label><input type="password" name="password_confirmation" class="form-control" required></div><button class="btn btn-primary">Change Password</button></form></div></div></div>@endcan
</div>@if($errors->any())<div class="alert alert-danger mt-3">{{ $errors->first() }}</div>@endif</div>
@endsection
